# Copyright (c) 2026 Alvin Brown & Clive Maxfield
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""test_coverage.py -- beboputer_tk.tools.coverage (Code Coverage utility).

Covers the .lst listing parser, the address->line map, and
CoverageSession's recording/reporting/attach-detach behaviour, plus a
regression check against a real shipped listing (Data/2funcal.lst) so
the row regex stays honest about the assembler's actual output format.
"""

import os

import pytest

from beboputer_v7.cpu import CPU
from beboputer_tk.tools.coverage import CoverageSession, LineCoverageMap, parse_listing
from compiler_core import Compiler

PROJECT_ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), '..'))

# A small program with one branch that is always taken (JZ, since ACC==5
# after CMPA $05 sets the Z flag) and one that is therefore never
# executed -- gives a deterministic covered/uncovered split to assert on.
BRANCHY_SRC = """.ORG $4000
        LDA    $05
        CMPA   $05
        JZ     [TAKEN]
        LDA    $FF
        HALT
TAKEN:  LDA    $01
        HALT
"""


def _run_to_halt(cpu, max_steps=1000):
    for _ in range(max_steps):
        if cpu.halted:
            break
        cpu.step()


def _load(cpu, compiled):
    cpu.reset()
    for i, b in enumerate(compiled.bytecode):
        cpu.ram[(compiled.origin + i) & 0xFFFF] = b
    cpu.pc = compiled.origin
    cpu.ram[0xF011] = 0xFF


# ---------------------------------------------------------------------------
# parse_listing / LineCoverageMap
# ---------------------------------------------------------------------------

def test_parse_listing_against_real_reference_file():
    """Data/2funcal.lst is a real, checked-in listing (not generated by
    this test) -- parsing it should find exactly the code/data lines
    it's known to contain, without mistaking any comment/header row for
    one (see coverage.py's _ROW_RE docstring for why that's the tricky
    part)."""
    lst_path = os.path.join(PROJECT_ROOT, 'Data', '2funcal.lst')
    with open(lst_path, encoding='latin-1') as fh:
        text = fh.read()

    rows = parse_listing(text)
    coded = [r for r in rows if r.addr is not None]
    assert coded, "expected at least one addressed row"

    # Line 25 is `4000 90 10     INIT:     LDA    CLRCODE` per the file.
    by_line = {r.line_no: r.addr for r in coded}
    assert by_line[25] == 0x4000

    # No comment/header/xref row (e.g. line 1 "#####...", or the blank
    # line 17) should have been mistaken for a coded line.
    assert 1 not in by_line
    assert 17 not in by_line


def test_line_coverage_map_bisects_multibyte_instructions():
    listing_text = Compiler().generate_listing(BRANCHY_SRC).text
    m = LineCoverageMap(parse_listing(listing_text))

    assert m.executable_lines == {2, 3, 4, 5, 6, 7, 8}
    assert m.address_for_line(2) == 0x4000
    assert m.address_for_line(4) == 0x4004    # JZ [TAKEN]

    # JZ is a 3-byte instruction ($D1 + 2-byte address) starting at
    # $4004 -- the operand bytes ($4005/$4006) belong to line 4 too,
    # even though only $4004 itself is a real "line start".
    assert m.line_for_address(0x4004) == 4
    assert m.line_for_address(0x4005) == 4
    assert m.line_for_address(0x4006) == 4
    assert m.line_for_address(0x4007) == 5     # next line's LDA $FF

    # An address before the program's own origin has no owning line.
    assert m.line_for_address(0x0000) is None


# ---------------------------------------------------------------------------
# CoverageSession
# ---------------------------------------------------------------------------

def test_coverage_session_from_source_reports_untaken_branch():
    session = CoverageSession.from_source(BRANCHY_SRC, source_path="branchy.asm")

    compiled = Compiler().compile_source(BRANCHY_SRC)
    cpu = CPU()
    _load(cpu, compiled)

    executed = session.run_headless(cpu, max_steps=1000)
    assert executed > 0
    assert cpu.halted

    rep = session.report()
    assert rep.total_executable == 7
    assert rep.covered == {2, 3, 4, 7, 8}
    assert rep.uncovered == {5, 6}
    assert rep.percent == pytest.approx(5 / 7 * 100)
    assert not rep.unmapped_addresses

    text = session.render_text_report(title="Branchy")
    assert "Coverage" in text
    assert "LDA    $FF" in text          # the uncovered line's source, quoted back

    annotated = session.render_annotated_source()
    lines = annotated.splitlines()
    assert lines[1].startswith("+")       # line 2, covered
    assert lines[4].startswith("!")       # line 5, uncovered
    assert lines[0].startswith(" ")       # line 1 (.ORG), not executable


def test_coverage_accumulates_across_multiple_runs_until_reset():
    """Matches the tool's actual use case: run a program more than once
    (different inputs/paths taken) and coverage should accumulate, not
    reset itself, until the caller explicitly asks it to."""
    session = CoverageSession.from_source(BRANCHY_SRC)
    compiled = Compiler().compile_source(BRANCHY_SRC)

    # First run: force the untaken branch by starting execution straight
    # from the "LDA $FF" line instead of the top, covering lines 5-6
    # without ever touching 2-4/7-8.
    cpu = CPU()
    _load(cpu, compiled)
    cpu.pc = compiled.origin + 7     # address of the "LDA $FF" line ($4007)
    session.run_headless(cpu, max_steps=1000)
    rep1 = session.report()
    assert rep1.covered == {5, 6}

    # Second run: the normal path (JZ taken) -- coverage should ADD to
    # the first run's hits, not replace them.
    cpu2 = CPU()
    _load(cpu2, compiled)
    session.run_headless(cpu2, max_steps=1000)
    rep2 = session.report()
    assert rep2.covered == {2, 3, 4, 5, 6, 7, 8}   # union of both runs
    assert rep2.uncovered == set()

    session.reset()
    rep3 = session.report()
    assert rep3.covered == set()
    assert len(rep3.uncovered) == rep3.total_executable == 7


def test_attach_wraps_and_detach_restores_cpu_step():
    session = CoverageSession.from_source(BRANCHY_SRC)
    compiled = Compiler().compile_source(BRANCHY_SRC)
    cpu = CPU()
    _load(cpu, compiled)

    original_step = cpu.step
    session.attach(cpu)
    assert session.attached
    assert cpu.step is not original_step

    _run_to_halt(cpu)
    rep = session.report()
    assert rep.covered == {2, 3, 4, 7, 8}

    session.detach()
    assert not session.attached
    # Bound methods aren't interned -- `is` would fail even when detach()
    # correctly restored the original method, since re-accessing cpu.step
    # mints a fresh bound-method wrapper each time. `==` compares
    # __self__/__func__, which is what actually matters here.
    assert cpu.step == original_step

    # Stepping after detach must NOT add further hits.
    cpu2 = CPU()
    _load(cpu2, compiled)
    cpu2.step()   # not tracked -- session was detached before this ran
    rep_after = session.report()
    assert rep_after.covered == {2, 3, 4, 7, 8}   # unchanged


def test_render_annotated_source_requires_source_lines():
    listing_text = Compiler().generate_listing(BRANCHY_SRC).text
    session = CoverageSession(listing_text)   # no source_lines passed
    with pytest.raises(RuntimeError):
        session.render_annotated_source()


def test_from_source_raises_on_bad_assembly():
    with pytest.raises(RuntimeError):
        CoverageSession.from_source(".ORG $4000\n        NOTAREALMNEMONIC\n")
