#FILE TYPE:DIY Calculator Buttons (*.ini) File
#GENERATOR:Beboputer v7
#DATE-TIME:Jun 12 11:14:24 2026
#SOURCEWAS:N/A

#COLOR CODES USED
#COLOR 0 = BLACK
#COLOR 1 = RED
#COLOR 2 = GREEN
#COLOR 3 = YELLOW
#COLOR 4 = BLUE
#COLOR 5 = MAGENTA
#COLOR 6 = CYAN


[Button 1]
Code= $40
Annotation=
Color= 0
Description=Unassigned

[Button 2]
Code= $41
Annotation=
Color= 0
Description=Unassigned

[Button 3]
Code= $42
Annotation=
Color= 0
Description=Unassigned

[Button 4]
Code= $43
Annotation=Bin
Color= 1
Description=Bin

[Button 5]
Code= $44
Annotation=Dec
Color= 1
Description=Dec Mode

[Button 6]
Code= $45
Annotation=Hex
Color= 1
Description=Hex Mode

[Button 7]
Code= $26
Annotation=
Color= 0
Description=Unassigned

[Button 8]
Code= $2B
Annotation=
Color= 0
Description=Unassigned

[Button 9]
Code= $30
Annotation=
Color= 0
Description=Unassigned

[Button 10]
Code= $35
Annotation=
Color= 0
Description=Unassigned

[Button 11]
Code= $25
Annotation=
Color= 5
Description=Unassigned

[Button 12]
Code= $2A
Annotation=
Color= 5
Description=Unassigned

[Button 13]
Code= $2F
Annotation=
Color= 0
Description=Unassigned

[Button 14]
Code= $34
Annotation=
Color= 0
Description=Unassigned

[Button 15]
Code= $24
Annotation=
Color= 0
Description=Unassigned

[Button 16]
Code= $29
Annotation=
Color= 0
Description=Unassigned

[Button 17]
Code= $2E
Annotation=
Color= 5
Description=Unassgned

[Button 18]
Code= $33
Annotation=
Color= 0
Description=Unassigned

[Button 19]
Code= $23
Annotation=
Color= 0
Description=Unassigned

[Button 20]
Code= $28
Annotation=
Color= 0
Description=Unassigned

[Button 21]
Code= $2D
Annotation=
Color= 0
Description=Unassigned

[Button 22]
Code= $32
Annotation=
Color= 0
Description=Unassigned

[Button 23]
Code= $22
Annotation=
Color= 5
Description=Unassigned

[Button 24]
Code= $27
Annotation=
Color= 5
Description=Unassgned

[Button 25]
Code= $2C
Annotation=
Color= 0
Description=Unassigned

[Button 26]
Code= $31
Annotation=
Color= 0
Description=Unassigned

[Button 27]
Code= $3A
Annotation=Sin
Color= 5
Description=Trig Function (Tan)

[Button 28]
Code= $39
Annotation=Cos
Color= 5
Description=Trig Function (Cos)

[Button 29]
Code= $38
Annotation=Tan
Color= 5
Description=Trig function (Tangent)

[Button 30]
Code= $37
Annotation=Log
Color= 5
Description=Log

[Button 31]
Code= $36
Annotation=n!
Color= 5
Description=Calculated Factorial

[Button 32]
Code= $3F
Annotation=x^y
Color= 5
Description=x to the y power

[Button 33]
Code= $3E
Annotation=x^3
Color= 5
Description=x cubied

[Button 34]
Code= $3D
Annotation=x^2
Color= 5
Description=x Square

[Button 35]
Code= $3C
Annotation=Rx
Color= 5
Description=Calculated square root of x

[Button 36]
Code= $3B
Annotation=1/x
Color= 5
Description=Calculated recriprial of x

[Button 37]
Code= $07
Annotation=7
Color= 0
Description=Binary, decimal, or hex digit

[Button 38]
Code= $08
Annotation=8
Color= 0
Description=Change sign

[Button 39]
Code= $09
Annotation=9
Color= 0
Description=Decimal (or radix) point

[Button 40]
Code= $19
Annotation=/
Color= 4
Description=Add

[Button 41]
Code= $1C
Annotation=Mod
Color= 5
Description=Equals

[Button 42]
Code= $21
Annotation=Exp
Color= 5
Description=Unassigned

[Button 43]
Code= $04
Annotation=4
Color= 0
Description=Binary, decimal, or hex digit

[Button 44]
Code= $05
Annotation=5
Color= 0
Description=Decimal or hexadecimal digit

[Button 45]
Code= $06
Annotation=6
Color= 0
Description=Decimal or hexadecimal digit

[Button 46]
Code= $17
Annotation=*
Color= 4
Description=Subtract

[Button 47]
Code= $1C
Annotation=Pi
Color= 5
Description=Left parenthesis

[Button 48]
Code= $20
Annotation=F-S
Color= 5
Description=Right parenthesis

[Button 49]
Code= $01
Annotation=1
Color= 0
Description=Decimal or hexadecimal digit

[Button 50]
Code= $02
Annotation=2
Color= 0
Description=Decimal or hexadecimal digit

[Button 51]
Code= $03
Annotation=3
Color= 0
Description=Decimal or hexadecimal digit

[Button 52]
Code= $17
Annotation=*
Color= 4
Description=Multiply

[Button 53]
Code= $1B
Annotation=(
Color= 5
Description=The constant Pi (3.14159...)

[Button 54]
Code= $1F
Annotation=)
Color= 5
Description=Scientific notation on/off

[Button 55]
Code= $00
Annotation=0
Color= 0
Description=Decimal or hexadecimal digit

[Button 56]
Code= $14
Annotation=+/-
Color= 4
Description=Decimal or hexadecimal digit

[Button 57]
Code= $15
Annotation=.
Color= 0
Description=Decimal or hexadecimal digit

[Button 58]
Code= $16
Annotation=-
Color= 4
Description=Divide

[Button 59]
Code= $1A
Annotation==
Color= 5
Description=Display remainder of division

[Button 60]
Code= $0A
Annotation=A
Color= 0
Description=Enter in scientific notation

[Button 61]
Code= $0B
Annotation=B
Color= 0
Description=Unassigned

[Button 62]
Code= $0C
Annotation=C
Color= 0
Description=Unassigned

[Button 63]
Code= $0D
Annotation=D
Color= 0
Description=Unassigned

[Button 64]
Code= $0E
Annotation=E
Color= 0
Description=Delete last character

[Button 65]
Code= $0F
Annotation=F
Color= 0
Description=Enter a value

[Button 66]
Code= $11
Annotation=Clear
Color= 1
Description=Clear Entry

[Button 67]
Code= $10
Annotation=CE
Color= 1
Description=CE

[Button 68]
Code= $12
Annotation=Back
Color= 1
Description=Back

[Button 69]
Code= $13
Annotation=Enter
Color= 1
Description=Enter
